### ISSUE TITLE
question

### ISSUE THREAD

**Issue by xadzkjdxlk** [vuejs/create-vue#229]
<template>
  <div id="app">
    < img src="./assets/logo.png">
    <router-view/>
  </div>
</template>

<script>
export default {
  name: 'App',
  data(){
    return{
      test:{
        number : 0,
      }
    }
  },
  methods:{
    init(){
      console.log(this.test);
      this.test.number = 10;
      console.log(this.test);
    }
  },
  mounted() {
    this.init();
  }
}
</script>

excuse me
how to solve the problem in idea
two console.log，the number is 10

**Comment by sodatea** [comment]
`console.log(this.test.number)`

It's because the object logged in the console is a live-binding, which only reflects the value when you click to expand. If you want to see an accurate output, you need to log the primitive value (`this.test.number`) rather than the object (`this.test`).

---

Next time, please ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://chat.vuejs.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js), or [StackOverflow](https://stackoverflow.com/questions/tagged/vue).
Github issues are for bug reports and feature requests only.
