### ISSUE TITLE
rename tsconfig.config.json to tsconfig.node.json

### ISSUE THREAD

**Issue by tjx666** [vuejs/create-vue#231]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/220999441-5945d2dd-7077-4788-bfcf-a049df40538b.png">

like `vue-ts` template:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/221000182-c85662f0-1ac1-496d-83c4-1824c5ca74f9.png">

**Comment by tjx666** [comment]
@sodatea If you feel it ok, I would like to make a pr

**Comment by sodatea** [comment]
Yeah, PR is welcome!

I initially named it `tsconfig.config.json` because I thought we might need to add some `types` to it (e.g., `vitest` if we want to configure it inside a `test` field in `vite.config.ts`), but it's never used so far.
So yeah, `tsconfig.node.json` may be more useful, and it's good to keep consistency with Vite templates.

**Comment by tjx666** [comment]
@sodatea pr review needed
