### ISSUE TITLE
Npm script `type-check` is not working

### ISSUE THREAD

**Issue by miroljub1995** [vuejs/create-vue#267]
Steps to reproduce:
* Create empty directory and navigate to it
* Run `npm init`
* Install `create-vue@latest`, currently it is `3.6.3`
* Run: `npx create-vue --ts --router --pinia --eslint-with-prettier source` and switch to `source` directory
*  Make some errors in files
* Run `npm run type-check`

There are no errors reported by command.

**Comment by filipbekic01** [comment]
Confirmed

**Comment by skirtles-code** [comment]
This seems to be a regression in 3.6.2. It works fine with `npm init vue@3.6.1`, but not 3.6.2 or 3.6.3.

**Comment by xenolithviktor** [comment]
A temporary workaround (from poking around in #181), in package.json scripts:
```
"type-check": "run-p type-check:*",
"type-check:app": "vue-tsc --noEmit -p tsconfig.app.json --composite false",
"type-check:node": "vue-tsc --noEmit -p tsconfig.node.json --composite false"
```

**Comment by Xujie990604** [comment]
I always thought my changes were causing the problem until I created a new project. Only to find out that brand new projects also have this problem

**Comment by filipbekic01** [comment]
Any progress? This is stopping us from using latest version.

**Comment by sodatea** [comment]
Sorry that somehow I missed the notification a few days ago.

It's because I moved the `compilerOptions` from `tsconfig.json` to `tsconfig.app.json` in the 2023-05-05 (v3.6.2) release, but forgot to change the `type-check` script.

There are a few ways to fix it:
- To restore the previous behavior, i.e. only check the `src` directory, please change the `type-check` script in `package.json` to `vue-tsc --noEmit -p tsconfig.app.json --composite false`
- A more comprehensive approach is to use `vue-tsc --build` for type-check now that `noEmit` is supported in composite projects in TypeScript 5. I've opened a PR: https://github.com/vuejs/create-vue/pull/274 to update the templates. To adopt this approach in an existing project, you can:
	1. add `*.tsbuildinfo` to the end of `.gitignore`
	2. add `"noEmit": true` to the `compilerOptions` in `tsconfig.app.json` and `tsconfig.node.json`
	3. change the `type-check` script in `package.json` to `vue-tsc --build`
Note that there's a small annoyance that an additional error message (`Error: Debug Failure. False expression: Paths must either both be absolute or both be relative`) would be output if there's a type error in a `.vue` file. It's just a misplaced error message, it doesn't mean any additional errors, nor will it throw when there's no error. I'm trying to fix that soon.
