### ISSUE TITLE
tsconfig.app.json error

### ISSUE THREAD

**Issue by yf339339** [vuejs/create-vue#286]
![image](https://github.com/vuejs/create-vue/assets/28554074/d4eba014-482a-43db-b32e-c458d532febc)

**Comment by btea** [comment]
Perhaps you should use the workspace typescript version 🤔

**Comment by Glenn8119** [comment]
I had the same issue and I found that this error is because the `tsconfig.json` file in `@vue/tsconfig` is now using the new feature of typescript 5.0 - `bundler` resolution.

After some search, according to this [stack overflow post](https://stackoverflow.com/questions/75870063/vscode-and-typescript-5-moduleresolution-bundler?newreg=63e0514b0d584cbea55aa548d8473919), this is just because old version of VSCode didn't support it yet,  so I just followed the answer and updated my VSCode and everything is fine now.
