### ISSUE TITLE
Cannot find module 'vue' in fresh Vue project with Typescript/ESLint

### ISSUE THREAD

**Issue by RGamberini** [vuejs/create-vue#341]
When creating a Vue / Typescript / ESLint project with create-vue it will have a `Cannot find module 'vue'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?ts(2792)` in it by default.

## Steps to Reproduce
1. Start a create-vue project with the following settings:
```
$ npm create vue@latest

Vue.js - The Progressive JavaScript Framework

√ Project name: ... create-vue-test
√ Add TypeScript? ... Yes
√ Add JSX Support? ... No
√ Add Vue Router for Single Page Application development? ... No
√ Add Pinia for state management? ... No
√ Add Vitest for Unit Testing? ... No
√ Add an End-to-End Testing Solution? » No
√ Add ESLint for code quality? ... Yes
√ Add Prettier for code formatting? ... Yes
```
2. Follow the installation steps.
3. [Following the `readme.md` enable Volar's takeover mode](https://github.com/vuejs/create-vue/blob/d757fcced310414cff824b49ef1e7c16e78fa3f9/utils/generateReadme.ts#L3-L16)

## Expected Behavior
An error free project.

## Current Behavior
There will be an error in VS Code in the `main.ts` file.
![image](https://github.com/vuejs/create-vue/assets/1889821/a123e60c-7d6e-40ff-ae5a-67e732d14d7a)

## Context (Environment)
Windows 10 19045
```
$ node --version
v18.13.0
$ npm --version
9.3.1
```

## Possible Solution
Under these conditions `compilerOptions.moduleResolution` in `tsconfig.app.json` should be set to `node` by default.

**Comment by Adi-ty** [comment]
I am not sure but the issue can because of different values of the moduleResolution option in the tsconfig.app.json and tsconfig.node.json files.

**Comment by sodatea** [comment]
Can't reproduce. Would you please check your TypeScript version, VS Code's built-in TypeScript version (or VS Code version), and your Volar version?

Because, according to the error message, you might be using an outdated TypeScript version.
The error message has been changed (from `node` to `nodenext`) since TypeScript 5.0 beta: https://github.com/microsoft/TypeScript/commit/e0bfac531b62a29e2747ed585eafb2e583923fd2#diff-fdf3f532dc2d3188ad1c05c8c9e064d0aa4143b8ba09b8f3313a0243f0a43effL3394

The most likely reason is an outdated VS Code version, because `create-vue` currently creates projects with TypeScript ~5.1.6, and Volar uses the built-in TypeScript version by default.
A workaround without updating VS Code is to choose the workspace version in the command palette:

<img width="605" alt="image" src="https://github.com/vuejs/create-vue/assets/3277634/edc3c9d2-5c22-4d46-aa9c-5e7fb491fd2f">
<img width="605" alt="image" src="https://github.com/vuejs/create-vue/assets/3277634/0ec98ba1-f1b2-4c2b-b56d-69f5cdaa5a5f">

**Comment by RGamberini** [comment]
@sodatea You were right! Somehow my VS Code version was badly out of date, running "Update Code" from the command palette and restarting VS Code seems to have fixed the bug.

Sorry for taking up your time, this is resolved!
